### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by dBHz01** [OrangeX4/simple-pinyin#1]
http://1.15.246.22:3367/ 似乎无法正常运行，错误如下：
<img width="763" alt="截屏2023-02-12 14 35 01" src="https://user-images.githubusercontent.com/61071017/218296871-fdbbae46-cc40-48ec-98f5-3c28bb1ba8b6.png">

**Comment by OrangeX4** [comment]
感谢提醒，已修复。
